version: '3.8'
services:
  psql:
    env_file:
      - .environments/psql.env
    volumes:
      - ../data/psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    build: 
      context: .
      dockerfile: ./WebApi/Dockerfile
    env_file:
      - .environments/api.env
    ports:
      - 80:8080
    depends_on:
      - psql

volumes:
  database: